version: '3.8'

services:
  #Nginx Service
  alegra-order-server:
    image: nginx:alpine
    container_name: alegra-order-server
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    networks:
      - alegra-network
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - alegra-order
      - alegra-order-db

  #MySQL Service
  alegra-order-db:
    image: mysql:latest
    container_name: alegra-order-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: alegra-order-db
      MYSQL_ROOT_PASSWORD: alegraDB
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - alegra-network
    volumes:
      - alegra-order-volume:/var/lib/mysql/

  #PHP Service
  alegra-order:
    build:
      context: .
    image: php:8.1-fpm
    container_name: alegra-order
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    ports:
      - "9000:9000"
    networks:
      - alegra-network
    volumes:
      - ./:/var/www/html/

  # Netshoot Service
  netshoot:
    image: nicolaka/netshoot
    container_name: netshoot-order-service
    restart: unless-stopped
    tty: true
    networks:
      - alegra-network

#Docker Networks
networks:
  alegra-network:
    driver: bridge

#Volumes
volumes:
  alegra-order-volume:
    driver: local
