version: '3.8'

services:
  #Nginx Service
  alegra-orders-server:
    image: nginx:alpine
    container_name: alegra-orders-server
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    networks:
      - alegra-network
    volumes:
      - ./:/var/www/html/
    depends_on:
      - alegra-orders
      - alegra-orders-db

  #MySQL Service
  alegra-orders-db:
    image: mysql:latest
    container_name: alegra-orders-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: alegra-orders-db
      MYSQL_ROOT_PASSWORD: alegraDB
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - alegra-network
    volumes:
      - alegra-db:/var/lib/mysql/

  #PHP Service
  alegra-orders:
    build:
      context: .
    image: php:8.1-fpm
    container_name: alegra-orders
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    ports:
      - "9000:9000"
    networks:
      - alegra-network
    volumes:
      - ./:/var/www/html/

  # Netshoot Service
  netshoot:
    image: nicolaka/netshoot
    container_name: netshoot-container
    restart: unless-stopped
    tty: true
    networks:
      - alegra-network

#Docker Networks
networks:
  alegra-network:
    driver: bridge

#Volumes
volumes:
  alegra-db:
    driver: local
